export enum ERR_TYPE {
  ERR_SIGNIN_REQUIRED = 'err_signin_required',
  ERR_SIGNIN_CREDENTIALS = 'err_signin_credentials',
  ERR_SUBSCRIPTION_REQUIRED = 'err_subscription_required',
  ERR_UNRELATED_TOKEN = 'err_unrelated_token',
  ERR_UNREADABLE_FIREBASE_TOKEN = 'err_unreadable_firebase_token',
  ERR_PRODUCT_NOT_FOUND = 'err_product_not_found',
  ERR_PURCHASE_ALREADY_EXISTS = 'err_purchase_already_exists',
  ERR_PURCHASE_NOT_FOUND = 'err_purchase_not_found',
  ERR_STORY_LIMIT = 'err_story_limit',
  ERR_INVALID_BIRTHDATE = 'err_invalid_birthdate',
  ERR_INVALID_PLACE = 'err_invalid_place',
  ERR_SERVICE_FAILED = 'err_service_failed',
  ERR_USER_NOT_FOUND = 'err_user_not_found',
  ERR_MISSING_FIELD = 'err_missing_field',
  ERR_MISSING_DEVICE_INFO = 'err_missing_device_info',
  ERR_UPDATE_REQUIRED = 'err_update_required',
  ERR_INCOMPLETE_STORY = 'err_incomplete_story',
  ERR_SESSION_EXPIRED = 'err_session_expired',
  ERR_ACCESS_FORBIDDEN = 'err_access_forbidden',
  ERR_UNKNOWN = 'err_unknown',
}

export const ERR_MESSAGES = {
  [ERR_TYPE.ERR_SIGNIN_REQUIRED]: 'You must be signed in',
  [ERR_TYPE.ERR_SIGNIN_CREDENTIALS]: 'Invalid user credentials',
  [ERR_TYPE.ERR_SUBSCRIPTION_REQUIRED]: 'You must be subscribed',
  [ERR_TYPE.ERR_UNRELATED_TOKEN]: 'Your refresh token is unrelated',
  [ERR_TYPE.ERR_UNREADABLE_FIREBASE_TOKEN]: 'Your firebase token is invalid',
  [ERR_TYPE.ERR_PRODUCT_NOT_FOUND]: 'Product not found',
  [ERR_TYPE.ERR_PURCHASE_ALREADY_EXISTS]: 'You already purchased this',
  [ERR_TYPE.ERR_PURCHASE_NOT_FOUND]: 'Purchase not found',
  [ERR_TYPE.ERR_STORY_LIMIT]: 'Story limit reached',
  [ERR_TYPE.ERR_INVALID_BIRTHDATE]: 'You must provide a valid birthdate',
  [ERR_TYPE.ERR_INVALID_PLACE]: 'You must provide a valid place',
  [ERR_TYPE.ERR_SERVICE_FAILED]: 'Third party API service failed',
  [ERR_TYPE.ERR_USER_NOT_FOUND]: 'Invalid user credentials',
  [ERR_TYPE.ERR_MISSING_FIELD]: 'Field(s) mismatch: #',
  [ERR_TYPE.ERR_MISSING_DEVICE_INFO]: 'Missing device info',
  [ERR_TYPE.ERR_UPDATE_REQUIRED]: 'Update required',
  [ERR_TYPE.ERR_INCOMPLETE_STORY]: 'Generated story incomplete',
  [ERR_TYPE.ERR_SESSION_EXPIRED]: 'Session expired',
  [ERR_TYPE.ERR_ACCESS_FORBIDDEN]: 'Access forbidden',
  [ERR_TYPE.ERR_UNKNOWN]: 'Unkown error',
};
